name: Sample Workflow

on:
  workflow_dispatch:
    inputs:
      paths:
        description: 'Comma-separated list of paths to run Terraform (e.g. "path/to/dir1, path/to/dir2"). Leave empty to include all services directories.'
        required: false
        default: ''
  pull_request:
    branches:
      - 'main'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check input from workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "Running Terraform for paths: ${{ github.event.inputs.paths }}"

      - name: Check pull_request event
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This is a pull request to the main branch."
