name: Test PR Creation

on:
  push:
    branches:
      - main

jobs:
  create_pr_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git User Info
        run: |
          git config user.email "you@example.com"
          git config user.name "Your Name"

      - name: Create New Branch
        run: |
          git checkout -b test-branch

      - name: Add Changes
        run: |
          echo "Test PR Creation" > test_pr.txt
          git add test_pr.txt
          git commit -m "Test PR Creation"

      - name: Push to Remote
        run: git push origin test-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Test PR Creation"
          branch: test-branch
          base: main
          title: "Test PR: Test PR Creation"
