name: Create PR with Unique Branch Name

on:
  push:
    branches:
      - main

jobs:
  create_pr_with_unique_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git User Info
        run: |
          git config user.email "yuto.matsuda04@gmail.com"
          git config user.name "Yuto Matsuda (GitHub Actions)"

      - name: Generate Unique Branch Name
        id: generate_branch_name
        run: |
          BRANCH_NAME="feature-$(date +%Y%m%d%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create New Branch
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}

      - name: Add Changes
        run: |
          echo "Unique branch name test" > test.txt
          git add test.txt
          git commit -m "Add test file with unique branch name"

      - name: Push to Remote
        run: git push origin ${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add test file with unique branch name"
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "PR: Test Unique Branch Name"
      
      - name: Debug Git Status
        run: git status

      - name: Debug Git Log
        run: git log --oneline -5

      # - name: Enable Auto-Merge
      #   run: |
      #     PR_NUMBER=$(gh pr list --base main --head ${{ env.BRANCH_NAME }} --json number --jq '.[0].number')
      #     gh pr merge $PR_NUMBER --auto
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
