name: Create and Merge Pull Request

on:
  push:
    branches:
      - main

jobs:
  create_and_merge:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git User Info
        run: |
          git config user.email "your.email@example.com"
          git config user.name "Your Name"

      - name: Create New Branch
        run: |
          git checkout -b new-feature-branch

      - name: Add Changes
        run: |
          echo "New content" > new_file.txt
          git add new_file.txt
          git commit -m "Add new file"

      - name: Push to Remote
        run: git push origin new-feature-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add new file"
          branch: new-feature-branch
          base: main
          title: "Feature: Add new file"

      - name: Merge Pull Request
        run: |
          PR_NUMBER=$(gh pr list --base main --head new-feature-branch --json number --jq '.[0].number')
          gh pr merge $PR_NUMBER --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
