name: Create Pull Request with Unique Branch

on:
  workflow_dispatch:

jobs:
  create_pr_with_unique_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git User Info
        run: |
          git config user.email "your.email@example.com"
          git config user.name "Your Name"

      - name: Generate Unique Branch Name
        id: generate_branch_name
        run: |
          BRANCH_NAME="feature-$(date +%Y%m%d%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create New Branch
        run: git checkout -b ${{ env.BRANCH_NAME }}

      - name: Add Changes and Commit
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d %H:%M:%S")
          echo "Current date and time: $CURRENT_DATE" > date_info.txt
          git add date_info.txt
          git commit -m "Add date information"

      - name: Push to Remote
        run: git push origin ${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add date information"
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "PR: Add Date Information"

      # - name: Set Auto-Merge
      #   if: env.ALREADY_EXIST != 1 && env.AUTO_MERGE == 'true'
      #   run: |
      #     PR_NUMBER=$(gh pr list --state open --base main --head ${{ env.BRANCH_NAME }} --json number --jq '.[0].number')
      #     gh pr merge $PR_NUMBER --auto

